### ISSUE TITLE
Screen shot using mouse based cross hairs and iframe

### ISSUE THREAD

**Issue by 767267** [lsbyerley/vue-screenshot#2]
Hi,

Can this lib be used to achieve in-application based screen shot of a part of html document using cross hairs based on mouse and having an iframe inside the html?

**Comment by lsbyerley** [comment]
The lib you will need is https://github.com/GoogleChrome/puppeteer

**Comment by 767267** [comment]
Thanks, but it has a dependency on Chromium.
